//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIT4_IMDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModelContainer : DbContext
    {
        public DBModelContainer()
            : base("name=DBModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FILM> FILMs { get; set; }
        public virtual DbSet<FILMTAAL> FILMTAALs { get; set; }
        public virtual DbSet<TAAL> TAALs { get; set; }
        public virtual DbSet<FILMTYPE> FILMTYPEs { get; set; }
        public virtual DbSet<TYPE> TYPEs { get; set; }
        public virtual DbSet<FILMREGISSEUR> FILMREGISSEURs { get; set; }
        public virtual DbSet<REGISSEUR> REGISSEURs { get; set; }
        public virtual DbSet<ROL> ROLs { get; set; }
        public virtual DbSet<ACTEUR> ACTEURs { get; set; }
        public virtual DbSet<BEOORDELING> BEOORDELINGs { get; set; }
        public virtual DbSet<GEBRUIKER> GEBRUIKERs1 { get; set; }
        public virtual DbSet<WIJZIGING> WIJZIGINGs { get; set; }
        public virtual DbSet<BLOCKED> BLOCKEDs { get; set; }
        public virtual DbSet<GROEPGEBRUIKER> GROEPGEBRUIKERs { get; set; }
        public virtual DbSet<GROEP> GROEPs { get; set; }
        public virtual DbSet<FILMGENRE> FILMGENREs { get; set; }
        public virtual DbSet<GENRE> GENREs { get; set; }
    }
}
