//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIT4_IMDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILMGENRE
    {
        public int FilmID { get; set; }
        public int GenreID { get; set; }
    
        public virtual GENRE GENRE { get; set; }
        public virtual FILM FILM { get; set; }
    }
}
