//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel.bu
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILMREGISSEUR
    {
        public int RegiID { get; set; }
        public int FilmID { get; set; }
    
        public virtual FILM FILM { get; set; }
        public virtual REGISSEUR REGISSEUR { get; set; }
    }
}
