//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel.bu
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FILM()
        {
            this.FILMTAALs = new HashSet<FILMTAAL>();
            this.FILMTYPEs = new HashSet<FILMTYPE>();
            this.FILMREGISSEURs = new HashSet<FILMREGISSEUR>();
            this.ROLs = new HashSet<ROL>();
            this.BEOORDELINGs = new HashSet<BEOORDELING>();
            this.FILMGENREs = new HashSet<FILMGENRE>();
        }
    
        public string IMDBNummer { get; set; }
        public string FilmNaam { get; set; }
        public int Duur { get; set; }
        public string Geluid { get; set; }
        public string AlternatieveNaam { get; set; }
        public string Poster { get; set; }
        public System.DateTime ToegevoegdDatum { get; set; }
        public int ToegevoegdDoor { get; set; }
        public string Versie { get; set; }
        public int GemiddeldeBeoordeling { get; set; }
        public int FilmID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILMTAAL> FILMTAALs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILMTYPE> FILMTYPEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILMREGISSEUR> FILMREGISSEURs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROL> ROLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BEOORDELING> BEOORDELINGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILMGENRE> FILMGENREs { get; set; }
    }
}
