//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel.bu
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEBRUIKER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GEBRUIKER()
        {
            this.BEOORDELINGs = new HashSet<BEOORDELING>();
            this.WIJZIGINGs = new HashSet<WIJZIGING>();
            this.BLOCKEDs = new HashSet<BLOCKED>();
            this.GROEPGEBRUIKERs = new HashSet<GROEPGEBRUIKER>();
        }
    
        public int GerbuikerID { get; set; }
        public string GebruikersNaam { get; set; }
        public string VoorNaam { get; set; }
        public string AchterNaam { get; set; }
        public System.DateTime Leeftijd { get; set; }
        public string EmailAdres { get; set; }
        public string WachtWoord { get; set; }
        public System.DateTime RegistratieDatum { get; set; }
        public int Rank { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BEOORDELING> BEOORDELINGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WIJZIGING> WIJZIGINGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BLOCKED> BLOCKEDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROEPGEBRUIKER> GROEPGEBRUIKERs { get; set; }
    }
}
