//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIT4_IMDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROEPGEBRUIKER
    {
        public int GroepID { get; set; }
        public int GebruikerID { get; set; }
    
        public virtual GROEP GROEP { get; set; }
        public virtual GEBRUIKER GEBRUIKER { get; set; }
    }
}
