//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIT4_IMDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROEP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GROEP()
        {
            this.GROEPGEBRUIKERs = new HashSet<GROEPGEBRUIKER>();
        }
    
        public int GroepID { get; set; }
        public string GroepNaam { get; set; }
        public System.DateTime AangemaaktDatum { get; set; }
        public int AangemaaktDoor { get; set; }
        public string GroepBeschrijving { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROEPGEBRUIKER> GROEPGEBRUIKERs { get; set; }
    }
}
