//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel.bu
{
    using System;
    using System.Collections.Generic;
    
    public partial class WIJZIGING
    {
        public int WijzigingID { get; set; }
        public int GebruikerID { get; set; }
        public string AangepasteEntiteit { get; set; }
        public string EntiteitID { get; set; }
        public string AangepasteVak { get; set; }
        public System.DateTime AanpasDatum { get; set; }
        public string OudData { get; set; }
        public string NieuwData { get; set; }
    
        public virtual GEBRUIKER GEBRUIKER { get; set; }
    }
}
